version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - echo running tests
      - npm test
  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
    - build/**/*
    - static-server.js
    - node_modules/**/*
    - package.json